package threads;
public class ResultTask extends Thread {
    public void run(){
        System.out.println("Result generated by: " +
                Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run(); // ❌ No new Thread
        t1.start(); // ✅ New Thread thread-0
    }
}
